title: Becoming a dad
description: My journey to becoming a dad and beyond
author: Downward Facing Dad
contact_email: becomingadadorg@gmail.com
about: I just become a dad and writing down my thoughts and experiences
disqus_shortname: becomingadad
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  resources:
    output: true
    permalink: /resource/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/becomingadadorg"

share:
  twitter_username: becomingadadorg
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Resources
      url: /resources/
    - text: XML Feed
      url: /feed.xml

url: "https://bacomingadad.org"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
